# Generated by Django 5.1.6 on 2025-02-18 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cadastros",
            "0002_remove_ofertacarona_vagas_remove_veiculo_capacidade_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
    ]
