# Generated by Django 5.1.6 on 2025-02-19 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0003_usuario_profile_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ofertacarona",
            name="veiculo",
        ),
        migrations.DeleteModel(
            name="Veiculo",
        ),
    ]
